BethanysPieShop/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using BethanysPieShop.Models;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BethanysPieShop.Controllers
{
    [Authorize]
    public class FeedbackController : Controller
    {
        private 
            IFeedbackRepository _feedbackRepository;

        public FeedbackController(IFeedbackRepository feedbackRepository)
        {
            _feedbackRepository = feedbackRepository;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _feedbackRepository.AddFeedback(feedback);
                return RedirectToAction("FeedbackComplete");
            }
            return View(feedback);
        }

        public IActionResult FeedbackComplete()
        {
            return View();
        }
    }
}

BethanysPieShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index" class="navbar-brand">Bethany's Pie Shop</a></li>
                    <li><a asp-controller="Feedback" asp-action="Index">Feedback</a></li>
                </ul>

                @if (SignInManager.IsSignedIn(User))
                {
                    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
                          method="post" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a id="registerLink" asp-controller="Account" asp-action="Register">Register</a></li>
                        <li><a id="loginLink" asp-controller="Account" asp-action="Login">Log in</a></li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
    </div>
</body>
</html>